### PR TITLE
#113: Link to issue preview in PR is sometimes duplicated (closes #113)

### LINKED ISSUE #113: Link to issue preview in PR is sometimes duplicated
## description
or triplicated

image

## how to reproduce
- usually switching tabs between `Commits` `Conversation` and `File changed` and (let the app) performing some ajax calls

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by francescogior**
Closes #113

### tests performed
- installed dev version locally
- switched to files changed tab in this pr
- switched between split/unified view and went back to conversation (usually brings to duplicated box)
- no duplicated box

### CODE REVIEW

File: src/plugin/addIssueDescriptionOnPrPage.js [hunk 1]
```diff
@@ -6,16 +6,13 @@ $(document).on('click', '.gwfp-issue-description-header', () => {
...
-    return;
-  }
   chrome.storage.sync.get({ githubToken: '', githubEnterpriseToken: '' }, ({ githubToken, githubEnterpriseToken }) => {
     const apiBaseUrl = !isEnterprise ? 'https://api.github.com/' : 'https://github.omnilab.our.buildo.io/api/v3/';
     const prTitle = $('.js-issue-title').text();
     const getIssueNumberRE = /.*\(closes\s#(\d+)\).*/;
     const [, associatedIssueNumber] = prTitle.match(getIssueNumberRE) || [];
     const apiToken = !isEnterprise ? githubToken : githubEnterpriseToken;
-    if (associatedIssueNumber) {
+    if (associatedIssueNumber && $('.gwfp-issue-description').length === 0) {
```
Comment (FrancescoCioria) [inline src/plugin/addIssueDescriptionOnPrPage.js]: wait, this way you're not duplicating it, but you're not updating it either, right?

I would always remove it and re-add it for safety as we're doing for other elements

Comment (francescogior) [inline src/plugin/addIssueDescriptionOnPrPage.js]: I think it rarely would affect the user experience but it makes sense to always update the fresh data. I'll fix it

**Comment by francescogior** [comment]
@FrancescoCioria ^
